#!/bin/bash
git clone --bare https://github.com/andlin78/cfg.git $HOME/.cfg
function config {
   /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME $@
}
mkdir -p .config-backup
config checkout
if [ $? = 0 ]; then
  echo "Checking out config.";
  else
    echo "Backing up pre-existing dot files.";
    config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} sh -c 'cp --parents -f {} .config-backup/ ; rm -f {}'
fi;
config checkout
if [ $? = 0 ]; then
   echo "All up to date."
   config config status.showUntrackedFiles no
else
   echo "Error while checking out.";
fi;
